name: Publish

on:
  push:
    tags:
    - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/delgan/qml-format:main
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Set ownership
      run: |
        # Workaround for https://github.com/actions/runner/issues/2033
        chown -R $(id -u):$(id -g) $PWD
    - name: Install dependencies
      run: npm install
    - name: Build Code
      run: npm run compile
    - name: Package Extension
      id: packageExtension
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: stub
        dryRun: true
    - name: Upload Extension Package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix
        path: ${{ steps.packageExtension.outputs.vsixPath }}

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-20.04
    environment:
      name: releasing
    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: vsix
        path: ${{ steps.packageExtension.outputs.vsixPath }}
    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
